### ISSUE TITLE
If no config (no cron) is present, strange and confusing errors are thrown by the API

### ISSUE THREAD

**Issue by mvintila** [syscollective/saltpeter#31]
```
Feb  9 23:07:42 salt saltpeter[1660380]: Uncaught exception GET /ws (127.0.0.1)
Feb  9 23:07:42 salt saltpeter[1660380]: HTTPServerRequest(protocol='http', host='salt.opsi.cl', method='GET', uri='/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
Feb  9 23:07:42 salt saltpeter[1660380]: Traceback (most recent call last):
Feb  9 23:07:42 salt saltpeter[1660380]:   File "/usr/lib/python3.9/multiprocessing/managers.py", line 801, in _callmethod
Feb  9 23:07:42 salt saltpeter[1660380]:     conn = self._tls.connection
Feb  9 23:07:42 salt saltpeter[1660380]: AttributeError: 'ForkAwareLocal' object has no attribute 'connection'
Feb  9 23:07:42 salt saltpeter[1660380]: During handling of the above exception, another exception occurred:
Feb  9 23:07:42 salt saltpeter[1660380]: Traceback (most recent call last):
Feb  9 23:07:42 salt saltpeter[1660380]:   File "/usr/local/lib/python3.9/dist-packages/tornado/websocket.py", line 942, in _accept_connection
Feb  9 23:07:42 salt saltpeter[1660380]:     open_result = handler.open(*handler.open_args, **handler.open_kwargs)
Feb  9 23:07:42 salt saltpeter[1660380]:   File "/usr/local/lib/python3.9/dist-packages/saltpeter/api.py", line 64, in open
Feb  9 23:07:42 salt saltpeter[1660380]:     self.write_message(json.dumps(dict({'config': dict(self.config), 'sp_version': __version__})))
Feb  9 23:07:42 salt saltpeter[1660380]:   File "<string>", line 2, in keys
Feb  9 23:07:42 salt saltpeter[1660380]:   File "/usr/lib/python3.9/multiprocessing/managers.py", line 805, in _callmethod
Feb  9 23:07:42 salt saltpeter[1660380]:     self._connect()
Feb  9 23:07:42 salt saltpeter[1660380]:   File "/usr/lib/python3.9/multiprocessing/managers.py", line 792, in _connect
Feb  9 23:07:42 salt saltpeter[1660380]:     conn = self._Client(self._token.address, authkey=self._authkey)
Feb  9 23:07:42 salt saltpeter[1660380]:   File "/usr/lib/python3.9/multiprocessing/connection.py", line 507, in Client
Feb  9 23:07:42 salt saltpeter[1660380]:     c = SocketClient(address)
Feb  9 23:07:42 salt saltpeter[1660380]:   File "/usr/lib/python3.9/multiprocessing/connection.py", line 635, in SocketClient
Feb  9 23:07:42 salt saltpeter[1660380]:     s.connect(address)
Feb  9 23:07:42 salt saltpeter[1660380]: ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by mvintila** [comment]
The workaround is to add at least 1 cron.

**Comment by mvintila** [comment]
This could not be reproduced on demand, the above case must have been a corner case. Will reopen if encountered again.
